### ISSUE TITLE
Icon is missing

### ISSUE THREAD

**Issue by F3der1co** [MikalDev/mikal_rotate_shape#1]
I prefer if there is a proper icon, I feel either would work fine:

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:360:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=rotate&icon.size=24&icon.color=%235f6368&icon.set=Material+Symbols

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:3d_rotation:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=3d&icon.size=24&icon.color=%235f6368&icon.set=Material+Symbols

**Comment by MikalDev** [comment]
The beauty of FOSS is that you can update it too, this is a good one to do, doesn't require changing code. I hope you submit a PR.

**Comment by F3der1co** [comment]
made a pull request:
https://github.com/MikalDev/mikal_rotate_shape/pull/3
